// <auto-generated />
using System;
using LeetLingo.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeetLingo.Api.Migrations
{
    [DbContext(typeof(LeetLingoContext))]
    partial class LeetLingoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeetLingo.Api.Problems.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FunctionSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCases")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Problems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467a-9ba2-0f1b1a1c7d21"),
                            FunctionSignature = "def solve(numbers: list[int], target: int) -> list[int]",
                            Slug = "two-sum",
                            Statement = "Given a list of integers and a target, return the indices of the two numbers that add up to the target.\n\nExactly one pair adds up to the target, and the same number may not be used twice. Return the two indices in ascending order.",
                            TestCases = "[{\"input\":[[2,7,11,15],9],\"expectedOutput\":[0,1]},{\"input\":[[3,2,4],6],\"expectedOutput\":[1,2]},{\"input\":[[3,3],6],\"expectedOutput\":[0,1]}]",
                            Title = "Two Sum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
